### ISSUE TITLE
Permission table seems no need to have a surrogate key.

### ISSUE THREAD

**Issue by FalseChord** [readr-media/readr-restful#101]
- We don't use keys to request single permission.
- The permission is usually predefined so the insertion cost is less concerned in the permission table.
According to the reason above, I think we don't need to add a surrogate key in the permission table.

**Comment by hcchien** [comment]
agree~

**Comment by ichiaohsu** [comment]
So maybe we could change it in the next database migration, @hcchien ?

**Comment by hcchien** [comment]
maybe we can create an issue in trello?

**Comment by ichiaohsu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate permission table](https://trello.com/c/ZGF9uvjr/251-migrate-permission-table)

**Comment by FalseChord** [comment]
The original surrogate primary key had been removed in patch file: 4_update_authors.up.sql
