### ISSUE TITLE
Make field customizable for /members/nickname

### ISSUE THREAD

**Issue by ichiaohsu** [readr-media/readr-restful#168]
Requested by @chiangkeith 
Include `mail` and `role` in `/members/nickname` API.
If possible, make field for this API customizable.

**Comment by ichiaohsu** [comment]
I don't get you, @chiangkeith 

Do you mean you want get the info about `custom_editor` of a member as well when using `/members/nickname` API？

If this is the case, you could simply add `"custom_editor"` in the fields array.

**Comment by chiangkeith** [comment]
yes, that's what i was talking about. ANd thanks a lot, already figured it out.
