### ISSUE TITLE
need objectName

### ISSUE THREAD

**Issue by chiangkeith** [readr-media/readr-restful#172]
if i call api `/points/:id`, i would get the data like:
```
{
    balance: -9267,
    created_at: "2018-06-19T07:58:59Z",
    id: 63,
    member_id: 648,
    object_id: 999944,
    object_type: 2,
    updated_at: "2018-06-19T07:58:59Z",
    updated_by: null
}
```

the problem is i need an extra property `object_name`, this can be referred to the title of the specific project. Would you Help, @ichiaohsu ?

**Comment by ichiaohsu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [作為會員，我希望可以看到我最近 100 筆的點數紀錄](https://trello.com/c/CxSuBHbj/210-%E4%BD%9C%E7%82%BA%E6%9C%83%E5%93%A1%EF%BC%8C%E6%88%91%E5%B8%8C%E6%9C%9B%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E6%88%91%E6%9C%80%E8%BF%91-100-%E7%AD%86%E7%9A%84%E9%BB%9E%E6%95%B8%E7%B4%80%E9%8C%84)
