### ISSUE TITLE
Project model types seem incorrect

### ISSUE THREAD

**Issue by ichiaohsu** [readr-media/readr-restful#183]
https://github.com/readr-media/readr-restful/blob/6e318d7a1e4239d07ac82f64d3859948c1c056c8/models/projects.go#L16-L21

Since member id is now int64 and published_at is `datetime` in db schema, it's very weird both `UpdatedBy` and `PublishedAt` are `NullString`. 

Idea?  @FalseChord

**Comment by FalseChord** [comment]
Should be fixed, will check this soon.
