### ISSUE TITLE
Accept a resource array query when calling /following/user

### ISSUE THREAD

**Issue by kwhsiung** [readr-media/readr-restful#228]
https://github.com/readr-media/readr-site-mobile/pull/271#pullrequestreview-149162964

## What problem does this feature solve?
Reduce api calls when we want to fetching a user follows by multiple resources at the same time like:
`GET /following/user?id=userId&resource=post`
`GET /following/user?id=userId&resource=report`
`GET /following/user?id=userId&resource=memo`
etc.

## What does the proposed API look like?
`GET /following/user?id=userId&resource=[post,report,memo]`

**Comment by ichiaohsu** [comment]
There is one uncertainty in this feature request: in original implementation when `resource=post` there is an extra argument `resource_type` that could filter whether the post type is `review`, `news`, `video`, `live`, while other resource doesn't.

Do you want to keep the term `resource_type` like this:
`GET /following/user?id=userId&resource=[post,report,memo]&resource_type=review`
here `resource_type` only denote the restriction for post.

Or should I change the term specifically to `post_type`, and the request looks like this:
`GET /following/user?id=userId&resource=[post,report,memo]&post_type=review`

Is this feature still in use? @kwhsiung  @hcchien

**Comment by kwhsiung** [comment]
I prefer keeping the term `resource_type`.
This feature is still used in profile's page.
