### ISSUE TITLE
[RFC] The API design for tag page

### ISSUE THREAD

**Issue by ichiaohsu** [readr-media/readr-restful#229]
**Feature name:** pnr

**Duration:**

**Proposer:** @chiangkeith @tempo0829 

**Related components:** Tag, Post, Report

**Related opinions:** 

## Motivation
Tag page need an API to return a sorted list of mixed Posts and Reports for load more feature. In this list the posts should be tagged with specific `tag`, and reports should belong to the project tagged with this `tag`. This list should be sorted in certain way considering simultaneously  the fields in Posts and Reports

## Detail
The API is named `pnr`, which means `Posts` and `Reports`. This API would be placed under `tag` API group.

It will need API consumer to pass tag id. Also It takes two common optional arguments: `max_result` and `sort`. The default is `max_result=20` and `sort=-published_at`. 

The usage of simplest form (and first page) is:
GET `/tags/pnr/{tag_id}` (it will default get 20 posts and reports in published_at desc order)

Once this API is triggered, it will make two function call sequentially to get `max_result` items in `sort` order from both posts and reports with the specific tag id. The results are two sorted list of posts and reports. Each posts and reports is picked into final list in designated sort order. 

The result of this API will have two key: `_items` and `_links`. `_items` holds the list of posts and reports. `_links` holds the *hateoas* information. When there are no more results than `max_result`, the content of `_links` is `{}`. When there are more results for **load more** feature, there will be auto-generated link for frontend to get the infos for next page, like this:
```json
"_links": {
    "next": {
        "url": "/tags/pnr/94?max_result=2&page=2&sort=-published_at&filter=pnr:published_at<=2018-06-26T05:57:40Z",
        "page": 2
    }
}
```
The `url` can be directly used in next request. The `page` is provided to frontend simply for current page information, while `page` argument does not affect SQL query.

Instead of passing `page` argument, I will use time to restrict value in special fields from both results when trying to get next results. The expected field is time type, and now I support `created_at`, `updated_at`, and `published`. 
 
## Unresolved questions
In next link, I use filter like this `published_at<=2018-05-22T05:55:03Z`. Using `<=` is to avoid issues when multiple posts and reports have identical `published_at`. But this will included the last post/report in previous API request, therefore there must be repeat results between two API requests.

Probable solutions is: 1. Filter repeat result on frontend. 2. Included extra `id` filter in `pnr` API to exclude last post/report id in sql query.

**Comment by ichiaohsu** [comment]
Any opinion? @hcchien @tempo0829

**Comment by hcchien** [comment]
we can filter repeat result in frontend so far.
