### ISSUE TITLE
Register Issue

### ISSUE THREAD

**Issue by chiangkeith** [readr-media/readr-restful#243]
**Describe the bug**
Couldn't register any ordinary member.

**To Reproduce**
Give a http req to POST/`register` with payload like:
```
{
    "nickname": "沈玉琳2",
    "mail": "shenyulin1@lin.com",
    "password": "ohoh",
    "register_mode": "ordinary"
}
```
And always get `400/Bad Request`

**Expected behavior**
Return 200.

**Comment by FalseChord** [comment]
PR #245 might fix this issue

**Comment by ichiaohsu** [comment]
Why not close this issue in #245 ...
