### ISSUE TITLE
GET chosen choice API

### ISSUE THREAD

**Issue by tempo0829** [readr-media/readr-restful#296]
## Spec
**usage:**
We need the API to get chosen choice by member id and poll id. The url like `/xxx?member_id=123&poll_id=1` or `/xxx?member_id=123&poll_id=in:[1,2,3,9]`. And this API need `created_at` filter. (`created_at=gte:2018-11-24T15:04:05Z,lt:2018-11-28T15:04:05Z`)

**Comment by ichiaohsu** [comment]
So @tempo0829 , for chosen choice API, you request filters for
1. single member_id
2. multiple poll_id (can I ask why you want to know what a member chooses for various polls?) 
3. created_at

IMHO, it seems unreasonable to allow multiple member_id here, so I'm not going to implement multiple member filter. I had two designs in mind for the route about these requests:
1. embedded parameter in url:
`/v2/polls/1,2,3,9/member/{member_id}/picks?created_at=gte:2018-11-24T15:04:05Z,lt:2018-11-28T15:04:05Z`
2. query parameters:
`/v2/polls/picks?member_id=123&poll_id=in:[1,2,3,9]&created_at=gte:2018-11-24T15:04:05Z,lt:2018-11-28T15:04:05Z`

I'll be appreciate if you have any opinion.

**Comment by tempo0829** [comment]
@ichiaohsu 
For multiple poll_id issue, we only need single poll_id in current situation. I just think about whether to retain flexibility, it's ok to only support single poll_id.

I prefer query parameters design, but if embedded parameter design has some advantages, you can use embedded design.

**Comment by ichiaohsu** [comment]
I think embedded design is for semantic reason. I will basically implement query parameters then.
