### ISSUE TITLE
Embed created_by info in GET polls API

### ISSUE THREAD

**Issue by ichiaohsu** [readr-media/readr-restful#302]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Requested by frontend to embed member detail in `created_by` field in polls API.

**Additional detail**
It's still unclear if there are more fields needed other than `name` for `created_by`.  If there is, should there be a filter to denote fields for `created_by`? 

Currently `embed` filter looks like `embed=choices`. If there are more fields to be embedded, what's the format of `embed` filter? Is `embed=choices,created_by&created_by_fields=[name, id...]` appropriate enough?

I once saw a guideline describing this, and it used `embed=choices,created_by(name,...)`. I'm still not sure if it's a genuine good design.
@tempo0829

**Comment by tempo0829** [comment]
@ichiaohsu @mmich
For `created_by`, we only need 'name' (member nickname) to show.  (confirmed)
I suggest add created_by `embed` filter to response created_by info (include member id, member nickname), but `created_by_fields=[name, id...]` filter is unnecessary.
